language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
# command to install dependencies
before_install:
  - sudo apt-get -y update -qq
  - sudo apt-get -y install -qq libzmq-dev
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: py.test
