language: python
python:
  - "2.7"
# command to install dependencies
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq libevent-dev
install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: tox
